### ISSUE TITLE
syntax error, unexpected identifier "int", expecting variable

### ISSUE THREAD

**Issue by KristoferStoimenov** [Label84/laravel-active-campaign#5]
Keep getting this error whenever I try to make any function call using this package.
I basically copy pasted the examples and this error shows, on tag list, on contact list

**Comment by tjardoo** [comment]
Hey, can you copy-paste the error your getting here. Then it's easier for for me to find out what and where to fix. Thanks

**Comment by KristoferStoimenov** [comment]
Hello, the error is in the title of my previous comment.

As I've seen there's some problems witht the data objects.

**Comment by tjardoo** [comment]
Could you copy-paste the full error stack trace here, that makes it easier to replicate this issue. Thanks
