### ISSUE TITLE
Create Field Value

### ISSUE THREAD

**Issue by yassinetrbls** [Label84/laravel-active-campaign#8]
Hello,

On AC API V3 : https://developers.activecampaign.com/reference/create-fieldvalue
Data to provide on POST : 
```
{
    "fieldValue": {
        "contact": 2,
        "field": 3,
        "value": "Blue"
    },
    "useDefaults": true
}
```
Why are you asking for different data ? "id" instead of "contact" ? What does this mean?

**Comment by tjardoo** [comment]
@yassinetrbls thanks for letting me know! The field name `contact` is the correct one (`id` was incorrect). I've updated this in v1.1.2.
